export const PROJECT_LIST = [
  {
    id: 8,
    img: "/project/MoMuk.webp",
    title: "MoMuk",
    tech: ["Next.js", "React", "TypeScript"],
    duration: "2025.08 ~ 2025.09",
    type: "personal",
    description:
      '"오늘 뭐 먹지?"에 대한 고민을 해결해주는 음식 랜덤 추천 및 결정 지원 서비스',
    site: "https://www.momuk.space/",
    github: "https://github.com/ckx9798/MoMuk",
  },
  {
    id: 7,
    img: "/project/LightestStore.webp",
    title: "LightestStore",
    tech: ["React", "JavaScript", "Zustand"],
    duration: "2025.08 ~ 2025.09",
    type: "personal",
    description:
      "불필요한 보일러플레이트 없이, 중앙화된 상태 저장소를 통해 즉시 전역상태 관리를 도입할 수 있는 경량 React 상태 관리 라이브러리",
    site: "https://www.npmjs.com/package/lighteststore",
    github: "https://github.com/ckx9798/LightestStore",
  },
  {
    id: 6,
    img: "/project/weLive.webp",
    title: "Welive",
    tech: ["Next.js", "TypeScript", "TanStack-Query", "TailwindCSS", "Zustand"],
    duration: "2025.05 ~ 2025.07",
    type: "team",
    members: 5,
    description: "주민들과 아파트 관리 단체를 위한 상호 관리 플랫폼",
    site: "https://project-welive-fe.vercel.app/",
    github: "https://github.com/codeit-bootcamp-nodejs/project-welive-fe",
  },
  {
    id: 1,
    img: "/project/SaveLinks.svg",
    title: "SaveLinks",
    tech: ["React", "TanStack-Query", "Chorom-storage", "Tailwind-CSS"],
    duration: "2025.01 ~ 2025.06",
    type: "personal",
    description:
      "유튜브, 인스타 등 숏폼 영상을 저장하여 한 페이지에서 관리하는 크롬 익스텐션",
    site: "https://www.savelinks.xyz",
    github: "https://github.com/ckx9798/SaveLinks",
  },
  {
    id: 2,
    img: "/project/momodal.svg",
    title: "momodal-library",
    tech: ["React", "TypeScript", "TanStack-Query", "NPM"],
    duration: "2025.02 ~ 2025.05",
    type: "personal",
    description:
      "알림 모달, 디자인 모달 등 다양한 모달 컴포넌트를 제공하는 React UI 라이브러리",
    site: "https://www.npmjs.com/package/momodal-library",
    github: "https://github.com/ckx9798/momodal-library",
  },
  {
    id: 3,
    img: "/project/GlobalNomad.svg",
    title: "GlobalNomad",
    tech: [
      "Next.js",
      "TypeScript",
      "TanStack-Query",
      "Zustand",
      "Tailwind-CSS",
    ],
    duration: "2024.11 ~ 2025.01",
    type: "team",
    members: 4,
    description:
      "원데이클래스, 액티비티 등 각종 체험을 등록하고 예약기능을 제공하는 웹사이트",
    site: "https://globalnomad.vercel.app/",
    github: "https://github.com/mungyun/globalnomad",
  },
  {
    id: 4,
    img: "/project/Taskify.svg",
    title: "Taskify",
    tech: ["Next.js", "TypeScript", "TanStack-Query"],
    duration: "2024.10 ~ 2024.11",
    type: "team",
    members: 4,
    description:
      "원데이클래스, 액티비티 등 각종 체험을 등록하고 예약기능을 제공하는 웹사이트",
    site: "https://taskify-sepia.vercel.app/login",
    github: "https://github.com/FE9-4Tential/Taskify",
  },
  {
    id: 5,
    img: "/project/FandomK.svg",
    title: "FandomK",
    tech: ["React", "JavaScript", "Styled-component", "Vite"],
    duration: "2024.08 ~ 2024.10",
    type: "team",
    members: 5,
    description:
      "크레딧으로 좋아하는 아이돌에게 인기투표, 후원하고 실시간 차트를 확인 할 수 있는 웹사이트",
    site: "https://fandom-k-9-4.netlify.app/",
    github: "https://github.com/ChungO5/Fandom-K",
  },
];
